# Site settings
title: mocking.design
email: mockingdesign@gmail.com
description: This is a descrip.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: malibuwill1024
github_username:  WillDosSantos
dribbble_username: willds

# Build settings
markdown: kramdown
